[package]
name = "pensieve-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "script"
path = "src/bin/script.rs"

[dependencies]
chrono = "0.4"
crossterm = "0.29.0"
duckdb = { version = "1.4.1", features = ["bundled"] }
mysql-binlog-connector-rust = "0.3.2"
ratatui = "0.29.0"
regex = "1.10"
